[build]
workingDirectory = "focoman-backend"

[[build.build]]
builder = "dockerfile"
dockerfilePath = "focoman-backend/Dockerfile"

[deploy]
startCommand = "java -jar app.jar"
healthcheckPath = "/api/studios/raj"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10