// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[studioSlug]/dashboard" | "/[studioSlug]/dashboard/crm" | "/[studioSlug]/dashboard/dev-portal" | "/[studioSlug]/dashboard/erp" | "/[studioSlug]/dashboard/marketplace" | "/[studioSlug]/dashboard/oms" | "/[studioSlug]/dashboard/reports" | "/[studioSlug]/dashboard/settings" | "/[studioSlug]/dashboard/whatsapp" | "/about" | "/account-settings" | "/checkout" | "/dashboard" | "/devportal" | "/features" | "/onboarding/join-studio" | "/onboarding/register-studio" | "/pricing" | "/sign-in" | "/studio/[slug]" | "/studios" | "/studios/[slug]" | "/track" | "/track/[passkey]" | "/workspaces"
type AppRouteHandlerRoutes = "/api/session"
type PageRoutes = never
type LayoutRoutes = "/" | "/[studioSlug]/dashboard" | "/[studioSlug]/dashboard/crm" | "/[studioSlug]/dashboard/dev-portal" | "/[studioSlug]/dashboard/erp" | "/[studioSlug]/dashboard/oms" | "/[studioSlug]/dashboard/whatsapp"
type RedirectRoutes = "/features" | "/marketplace" | "/marketplace/[slug]" | "/pricing"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[studioSlug]/dashboard": { "studioSlug": string; }
  "/[studioSlug]/dashboard/crm": { "studioSlug": string; }
  "/[studioSlug]/dashboard/dev-portal": { "studioSlug": string; }
  "/[studioSlug]/dashboard/erp": { "studioSlug": string; }
  "/[studioSlug]/dashboard/marketplace": { "studioSlug": string; }
  "/[studioSlug]/dashboard/oms": { "studioSlug": string; }
  "/[studioSlug]/dashboard/reports": { "studioSlug": string; }
  "/[studioSlug]/dashboard/settings": { "studioSlug": string; }
  "/[studioSlug]/dashboard/whatsapp": { "studioSlug": string; }
  "/about": {}
  "/account-settings": {}
  "/api/session": {}
  "/checkout": {}
  "/dashboard": {}
  "/devportal": {}
  "/features": {}
  "/marketplace": {}
  "/marketplace/[slug]": { "slug": string; }
  "/onboarding/join-studio": {}
  "/onboarding/register-studio": {}
  "/pricing": {}
  "/sign-in": {}
  "/studio/[slug]": { "slug": string; }
  "/studios": {}
  "/studios/[slug]": { "slug": string; }
  "/track": {}
  "/track/[passkey]": { "passkey": string; }
  "/workspaces": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[studioSlug]/dashboard": never
  "/[studioSlug]/dashboard/crm": never
  "/[studioSlug]/dashboard/dev-portal": never
  "/[studioSlug]/dashboard/erp": never
  "/[studioSlug]/dashboard/oms": never
  "/[studioSlug]/dashboard/whatsapp": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
