// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[studioSlug]/dashboard/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[studioSlug]/dashboard/crm">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/dev-portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[studioSlug]/dashboard/dev-portal">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/dev-portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/erp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[studioSlug]/dashboard/erp">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/erp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[studioSlug]/dashboard/marketplace">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/oms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[studioSlug]/dashboard/oms">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/oms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[studioSlug]/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[studioSlug]/dashboard/reports">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[studioSlug]/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/whatsapp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[studioSlug]/dashboard/whatsapp">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/whatsapp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account-settings">> = Specific
  const handler = {} as typeof import("../../src/app/account-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/devportal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devportal">> = Specific
  const handler = {} as typeof import("../../src/app/devportal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features">> = Specific
  const handler = {} as typeof import("../../src/app/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/join-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/join-studio">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/join-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/register-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/register-studio">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/register-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../src/app/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/studio/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/studio/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/studios/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studios/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/studios/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/studios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studios">> = Specific
  const handler = {} as typeof import("../../src/app/studios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/track/[passkey]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/track/[passkey]">> = Specific
  const handler = {} as typeof import("../../src/app/track/[passkey]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/track/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/track">> = Specific
  const handler = {} as typeof import("../../src/app/track/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspaces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspaces">> = Specific
  const handler = {} as typeof import("../../src/app/workspaces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/[studioSlug]/dashboard/crm/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[studioSlug]/dashboard/crm">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/crm/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/dev-portal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[studioSlug]/dashboard/dev-portal">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/dev-portal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/erp/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[studioSlug]/dashboard/erp">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/erp/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[studioSlug]/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/oms/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[studioSlug]/dashboard/oms">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/oms/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[studioSlug]/dashboard/whatsapp/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[studioSlug]/dashboard/whatsapp">> = Specific
  const handler = {} as typeof import("../../src/app/[studioSlug]/dashboard/whatsapp/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
