import { Studio, Customer, StudioMember, Order, Task } from "@focoman/types";

export const DEMO_STUDIO_SLUG = "lumina-studios";

export const DEMO_STUDIO: Studio = {
  id: "lumina-studios",
  name: "Lumina Creative Studio",
  city: "Bengaluru, Karnataka",
  ownerId: "demo-user-arjun",
  ownerName: "Arjun Sharma",
  ownerEmail: "arjun@luminastudios.com",
  ownerPhone: "+91 98765 43210",
  whatsappConfig: {
    masterEnabled: true,
    upcoming_3day: true,
    post_event_start: true,
    raw_photos_sent: true,
    customer_selection_done: true,
    album_review_done: true,
    ready_for_delivery: true,
    assignment_confirm: true,
    task_assigned: true,
    customer_post_event: true,
    customer_ready_delivery: true,
    customer_payment_remind: true,
  },
  createdAt: "2026-01-10T10:00:00.000Z",
  updatedAt: "2026-09-01T12:00:00.000Z",
};

export interface DemoUserPersona {
  uid: string;
  name: string;
  email: string;
  role: "STUDIO_OWNER" | "STUDIO_MEMBER";
  title: string;
  avatarText: string;
  skills?: string[];
}

export const DEMO_USER_PERSONAS: DemoUserPersona[] = [
  {
    uid: "demo-user-arjun",
    name: "Arjun Sharma",
    email: "arjun@luminastudios.com",
    role: "STUDIO_OWNER",
    title: "Studio Owner & Creative Director",
    avatarText: "AS",
    skills: ["PHOTOGRAPHY", "VIDEOGRAPHY"],
  },
  {
    uid: "demo-user-priya",
    name: "Priya Nair",
    email: "priya@luminastudios.com",
    role: "STUDIO_MEMBER",
    title: "Lead Wedding Photographer",
    avatarText: "PN",
    skills: ["PHOTOGRAPHY", "PHOTO_EDITING"],
  },
  {
    uid: "demo-user-rohan",
    name: "Rohan Mehta",
    email: "rohan@luminastudios.com",
    role: "STUDIO_MEMBER",
    title: "Senior Colorist & Retoucher",
    avatarText: "RM",
    skills: ["PHOTO_EDITING", "ALBUM_DESIGN"],
  },
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: "CUS-LUM-001",
    studioId: "lumina-studios",
    name: "Ananya & Kabir Roy",
    phone: "+91 98123 45678",
    email: "ananya.roy@example.com",
    address: "Palace Grounds, Jayamahal, Bengaluru",
    createdAt: "2026-07-15T09:30:00.000Z",
    updatedAt: "2026-08-01T11:00:00.000Z",
  },
  {
    id: "CUS-LUM-002",
    studioId: "lumina-studios",
    name: "TechCorp Global (Vikram Verma)",
    phone: "+91 98234 56789",
    email: "vikram.v@techcorp.com",
    address: "Prestige Shantiniketan, Whitefield, Bengaluru",
    createdAt: "2026-07-20T14:15:00.000Z",
    updatedAt: "2026-08-10T16:20:00.000Z",
  },
  {
    id: "CUS-LUM-003",
    studioId: "lumina-studios",
    name: "Rohan & Meera Singhania",
    phone: "+91 98345 67890",
    email: "rohan.singhania@example.com",
    address: "12th Main, Indiranagar, Bengaluru",
    createdAt: "2026-08-02T10:00:00.000Z",
    updatedAt: "2026-08-25T15:30:00.000Z",
  },
  {
    id: "CUS-LUM-004",
    studioId: "lumina-studios",
    name: "Aditi & Sameer Sharma",
    phone: "+91 98456 78901",
    email: "aditi.sharma@example.com",
    address: "5th Block, Koramangala, Bengaluru",
    createdAt: "2026-06-10T11:45:00.000Z",
    updatedAt: "2026-08-22T14:00:00.000Z",
  },
  {
    id: "CUS-LUM-005",
    studioId: "lumina-studios",
    name: "Zara Autumn Lookbook (Kavya Das)",
    phone: "+91 98567 89012",
    email: "creative@zara-india.com",
    address: "UB City Collection Studio, Bengaluru",
    createdAt: "2026-08-18T16:00:00.000Z",
    updatedAt: "2026-09-02T10:15:00.000Z",
  },
  {
    id: "CUS-LUM-006",
    studioId: "lumina-studios",
    name: "Vikram Malhotra 50th Jubilee",
    phone: "+91 98678 90123",
    email: "vm.malhotra@example.com",
    address: "Sadashivanagar, Bengaluru",
    createdAt: "2026-05-20T08:00:00.000Z",
    updatedAt: "2026-08-15T12:00:00.000Z",
  },
];

export const DEMO_MEMBERS: StudioMember[] = [
  {
    id: "demo-user-arjun",
    studioId: "lumina-studios",
    name: "Arjun Sharma",
    email: "arjun@luminastudios.com",
    phone: "+91 98765 43210",
    skills: ["PHOTOGRAPHY", "VIDEOGRAPHY"],
    createdAt: "2026-01-10T10:00:00.000Z",
    updatedAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "demo-user-priya",
    studioId: "lumina-studios",
    name: "Priya Nair",
    email: "priya@luminastudios.com",
    phone: "+91 98765 43211",
    skills: ["PHOTOGRAPHY", "PHOTO_EDITING"],
    createdAt: "2026-02-15T11:00:00.000Z",
    updatedAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "demo-user-rohan",
    studioId: "lumina-studios",
    name: "Rohan Mehta",
    email: "rohan@luminastudios.com",
    phone: "+91 98765 43212",
    skills: ["PHOTO_EDITING", "ALBUM_DESIGN"],
    createdAt: "2026-03-01T09:30:00.000Z",
    updatedAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "demo-user-aisha",
    studioId: "lumina-studios",
    name: "Aisha Khan",
    email: "aisha@luminastudios.com",
    phone: "+91 98765 43213",
    skills: ["VIDEOGRAPHY"],
    createdAt: "2026-04-10T14:20:00.000Z",
    updatedAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "demo-user-deepak",
    studioId: "lumina-studios",
    name: "Deepak Verma",
    email: "deepak@luminastudios.com",
    phone: "+91 98765 43214",
    skills: ["ALBUM_DESIGN"],
    createdAt: "2026-05-18T16:00:00.000Z",
    updatedAt: "2026-08-01T10:00:00.000Z",
  },
];

export const DEMO_ORDERS: Order[] = [
  {
    id: "ORD-LUM-101",
    studioId: "lumina-studios",
    orderNumber: "ORD-LUM-101",
    customer: {
      id: "CUS-LUM-001",
      name: "Ananya & Kabir Roy",
      phone: "+91 98123 45678",
    },
    eventType: "Grand Wedding & Reception",
    eventDate: "2026-10-18",
    eventLocation: "Palace Grounds, Jayamahal, Bengaluru",
    services: ["Photography", "Videography", "Album"],
    packages: ["Traditional Wedding Complete"],
    pricing: {
      estimatedPrice: 160000,
      finalConfirmedPrice: 150000,
      advanceAmount: 50000,
      remainingAmount: 100000,
    },
    paymentStatus: "PAYMENT_CONFIRMATION_REQUIRED",
    orderStatus: "AWAITING_EVENT",
    assignedResources: [
      {
        memberId: "demo-user-arjun",
        memberName: "Arjun Sharma",
        skill: "PHOTOGRAPHY",
        availabilityConfirmed: true,
      },
      {
        memberId: "demo-user-priya",
        memberName: "Priya Nair",
        skill: "PHOTOGRAPHY",
        availabilityConfirmed: true,
      },
      {
        memberId: "demo-user-aisha",
        memberName: "Aisha Khan",
        skill: "VIDEOGRAPHY",
        availabilityConfirmed: true,
      },
    ],
    trackingPasskey: "FOC-DEMO-01",
    createdAt: "2026-08-10T10:00:00.000Z",
    updatedAt: "2026-09-01T15:00:00.000Z",
  },
  {
    id: "ORD-LUM-102",
    studioId: "lumina-studios",
    orderNumber: "ORD-LUM-102",
    customer: {
      id: "CUS-LUM-002",
      name: "TechCorp Global (Vikram Verma)",
      phone: "+91 98234 56789",
    },
    eventType: "Annual Leadership Summit",
    eventDate: "2026-09-02",
    eventLocation: "Prestige Shantiniketan, Whitefield, Bengaluru",
    services: ["Photography", "Videography"],
    packages: ["Corporate Executive Coverage"],
    pricing: {
      estimatedPrice: 80000,
      finalConfirmedPrice: 75000,
      advanceAmount: 35000,
      remainingAmount: 40000,
    },
    paymentStatus: "PAYMENT_CONFIRMATION_REQUIRED",
    orderStatus: "POST_EVENT_IN_PROGRESS",
    assignedResources: [
      {
        memberId: "demo-user-priya",
        memberName: "Priya Nair",
        skill: "PHOTOGRAPHY",
        availabilityConfirmed: true,
      },
      {
        memberId: "demo-user-rohan",
        memberName: "Rohan Mehta",
        skill: "PHOTO_EDITING",
        availabilityConfirmed: true,
      },
    ],
    trackingPasskey: "FOC-DEMO-02",
    createdAt: "2026-08-12T14:30:00.000Z",
    updatedAt: "2026-09-04T09:00:00.000Z",
  },
  {
    id: "ORD-LUM-103",
    studioId: "lumina-studios",
    orderNumber: "ORD-LUM-103",
    customer: {
      id: "CUS-LUM-003",
      name: "Rohan & Meera Singhania",
      phone: "+91 98345 67890",
    },
    eventType: "Sunset Pre-Wedding Cinema",
    eventDate: "2026-09-05",
    eventLocation: "Nandi Hills Sunrise Point & Resort",
    services: ["Photography", "Videography", "Album"],
    packages: ["Cinematic Romance Pack"],
    pricing: {
      estimatedPrice: 60000,
      finalConfirmedPrice: 55000,
      advanceAmount: 55000,
      remainingAmount: 0,
    },
    paymentStatus: "PAYMENT_COMPLETED",
    orderStatus: "POST_EVENT_IN_PROGRESS",
    assignedResources: [
      {
        memberId: "demo-user-arjun",
        memberName: "Arjun Sharma",
        skill: "PHOTOGRAPHY",
        availabilityConfirmed: true,
      },
      {
        memberId: "demo-user-aisha",
        memberName: "Aisha Khan",
        skill: "VIDEOGRAPHY",
        availabilityConfirmed: true,
      },
      {
        memberId: "demo-user-deepak",
        memberName: "Deepak Verma",
        skill: "ALBUM_DESIGN",
        availabilityConfirmed: true,
      },
    ],
    trackingPasskey: "FOC-DEMO-03",
    createdAt: "2026-08-20T11:00:00.000Z",
    updatedAt: "2026-09-06T18:00:00.000Z",
  },
  {
    id: "ORD-LUM-104",
    studioId: "lumina-studios",
    orderNumber: "ORD-LUM-104",
    customer: {
      id: "CUS-LUM-004",
      name: "Aditi & Sameer Sharma",
      phone: "+91 98456 78901",
    },
    eventType: "Outdoor Maternity & Family Portrait",
    eventDate: "2026-08-18",
    eventLocation: "Cubbon Park Heritage Pavilion, Bengaluru",
    services: ["Photography", "Album"],
    packages: ["Family Heritage Bundle"],
    pricing: {
      estimatedPrice: 35000,
      finalConfirmedPrice: 35000,
      advanceAmount: 35000,
      remainingAmount: 0,
    },
    paymentStatus: "PAYMENT_COMPLETED",
    orderStatus: "COMPLETED",
    assignedResources: [
      {
        memberId: "demo-user-priya",
        memberName: "Priya Nair",
        skill: "PHOTOGRAPHY",
        availabilityConfirmed: true,
      },
      {
        memberId: "demo-user-rohan",
        memberName: "Rohan Mehta",
        skill: "PHOTO_EDITING",
        availabilityConfirmed: true,
      },
    ],
    trackingPasskey: "FOC-DEMO-04",
    createdAt: "2026-07-28T09:00:00.000Z",
    updatedAt: "2026-08-28T16:00:00.000Z",
  },
  {
    id: "ORD-LUM-105",
    studioId: "lumina-studios",
    orderNumber: "ORD-LUM-105",
    customer: {
      id: "CUS-LUM-005",
      name: "Zara Autumn Lookbook (Kavya Das)",
      phone: "+91 98567 89012",
    },
    eventType: "Editorial Fashion Lookbook Shoot",
    eventDate: "2026-10-25",
    eventLocation: "UB City Central Atrium & Rooftop",
    services: ["Photography", "Videography"],
    packages: ["Commercial Fashion Portfolio"],
    pricing: {
      estimatedPrice: 95000,
      finalConfirmedPrice: 90000,
      advanceAmount: 45000,
      remainingAmount: 45000,
    },
    paymentStatus: "PAYMENT_CONFIRMATION_REQUIRED",
    orderStatus: "AWAITING_EVENT",
    assignedResources: [
      {
        memberId: "demo-user-arjun",
        memberName: "Arjun Sharma",
        skill: "PHOTOGRAPHY",
        availabilityConfirmed: true,
      },
      {
        memberId: "demo-user-aisha",
        memberName: "Aisha Khan",
        skill: "VIDEOGRAPHY",
        availabilityConfirmed: null,
      },
    ],
    trackingPasskey: "FOC-DEMO-05",
    createdAt: "2026-08-25T13:00:00.000Z",
    updatedAt: "2026-09-02T11:30:00.000Z",
  },
  {
    id: "ORD-LUM-106",
    studioId: "lumina-studios",
    orderNumber: "ORD-LUM-106",
    customer: {
      id: "CUS-LUM-006",
      name: "Vikram Malhotra 50th Jubilee",
      phone: "+91 98678 90123",
    },
    eventType: "Golden Jubilee Celebration & Gala",
    eventDate: "2026-08-08",
    eventLocation: "Taj West End Gardens, Bengaluru",
    services: ["Photography", "Videography", "Album"],
    packages: ["Signature Luxury Gala"],
    pricing: {
      estimatedPrice: 70000,
      finalConfirmedPrice: 65000,
      advanceAmount: 65000,
      remainingAmount: 0,
    },
    paymentStatus: "PAYMENT_COMPLETED",
    orderStatus: "COMPLETED",
    assignedResources: [
      {
        memberId: "demo-user-arjun",
        memberName: "Arjun Sharma",
        skill: "PHOTOGRAPHY",
        availabilityConfirmed: true,
      },
      {
        memberId: "demo-user-priya",
        memberName: "Priya Nair",
        skill: "PHOTOGRAPHY",
        availabilityConfirmed: true,
      },
      {
        memberId: "demo-user-deepak",
        memberName: "Deepak Verma",
        skill: "ALBUM_DESIGN",
        availabilityConfirmed: true,
      },
    ],
    trackingPasskey: "FOC-DEMO-06",
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-08-18T17:00:00.000Z",
  },
];

export const DEMO_TASKS: Task[] = [
  // ORD-LUM-101 (Awaiting Event)
  {
    id: "TSK-LUM-101-1",
    orderId: "ORD-LUM-101",
    studioId: "lumina-studios",
    title: "RAW Photos Review & Selection",
    serviceCategory: "PHOTOGRAPHY",
    assignedMemberId: "demo-user-priya",
    assignedMemberName: "Priya Nair",
    status: "ASSIGNED",
    sequenceOrder: 1,
    createdAt: "2026-08-10T10:00:00.000Z",
    updatedAt: "2026-08-10T10:00:00.000Z",
  },
  {
    id: "TSK-LUM-101-2",
    orderId: "ORD-LUM-101",
    studioId: "lumina-studios",
    title: "Photo Editing & Color Retouching",
    serviceCategory: "PHOTOGRAPHY",
    assignedMemberId: "demo-user-rohan",
    assignedMemberName: "Rohan Mehta",
    status: "ASSIGNED",
    sequenceOrder: 2,
    createdAt: "2026-08-10T10:00:00.000Z",
    updatedAt: "2026-08-10T10:00:00.000Z",
  },
  {
    id: "TSK-LUM-101-3",
    orderId: "ORD-LUM-101",
    studioId: "lumina-studios",
    title: "Cinematic Highlight Video Editing",
    serviceCategory: "VIDEOGRAPHY",
    assignedMemberId: "demo-user-aisha",
    assignedMemberName: "Aisha Khan",
    status: "ASSIGNED",
    sequenceOrder: 3,
    createdAt: "2026-08-10T10:00:00.000Z",
    updatedAt: "2026-08-10T10:00:00.000Z",
  },
  {
    id: "TSK-LUM-101-4",
    orderId: "ORD-LUM-101",
    studioId: "lumina-studios",
    title: "Album Preparation & Layout Design",
    serviceCategory: "ALBUM",
    assignedMemberId: "demo-user-deepak",
    assignedMemberName: "Deepak Verma",
    status: "ASSIGNED",
    sequenceOrder: 4,
    createdAt: "2026-08-10T10:00:00.000Z",
    updatedAt: "2026-08-10T10:00:00.000Z",
  },

  // ORD-LUM-102 (Post-Event In Progress)
  {
    id: "TSK-LUM-102-1",
    orderId: "ORD-LUM-102",
    studioId: "lumina-studios",
    title: "RAW Photos Review & Selection",
    serviceCategory: "PHOTOGRAPHY",
    assignedMemberId: "demo-user-priya",
    assignedMemberName: "Priya Nair",
    status: "COMPLETED",
    sequenceOrder: 1,
    createdAt: "2026-08-12T14:30:00.000Z",
    updatedAt: "2026-09-03T11:00:00.000Z",
  },
  {
    id: "TSK-LUM-102-2",
    orderId: "ORD-LUM-102",
    studioId: "lumina-studios",
    title: "Keynote & Speaker Photo Retouching",
    serviceCategory: "PHOTOGRAPHY",
    assignedMemberId: "demo-user-rohan",
    assignedMemberName: "Rohan Mehta",
    status: "IN_PROGRESS",
    sequenceOrder: 2,
    createdAt: "2026-08-12T14:30:00.000Z",
    updatedAt: "2026-09-04T10:00:00.000Z",
  },
  {
    id: "TSK-LUM-102-3",
    orderId: "ORD-LUM-102",
    studioId: "lumina-studios",
    title: "Executive Summit Highlight Reel",
    serviceCategory: "VIDEOGRAPHY",
    assignedMemberId: "demo-user-aisha",
    assignedMemberName: "Aisha Khan",
    status: "ASSIGNED",
    sequenceOrder: 3,
    createdAt: "2026-08-12T14:30:00.000Z",
    updatedAt: "2026-09-02T15:00:00.000Z",
  },

  // ORD-LUM-103 (Post-Event In Progress)
  {
    id: "TSK-LUM-103-1",
    orderId: "ORD-LUM-103",
    studioId: "lumina-studios",
    title: "RAW Photos Review & Selection",
    serviceCategory: "PHOTOGRAPHY",
    assignedMemberId: "demo-user-arjun",
    assignedMemberName: "Arjun Sharma",
    status: "COMPLETED",
    sequenceOrder: 1,
    createdAt: "2026-08-20T11:00:00.000Z",
    updatedAt: "2026-09-06T10:00:00.000Z",
  },
  {
    id: "TSK-LUM-103-2",
    orderId: "ORD-LUM-103",
    studioId: "lumina-studios",
    title: "Sunset Cinematic Teaser Color Grade",
    serviceCategory: "VIDEOGRAPHY",
    assignedMemberId: "demo-user-aisha",
    assignedMemberName: "Aisha Khan",
    status: "REVIEW",
    sequenceOrder: 2,
    reworkNotes: "Couple requested warmer golden hour tones on clip #4.",
    createdAt: "2026-08-20T11:00:00.000Z",
    updatedAt: "2026-09-07T14:00:00.000Z",
  },
  {
    id: "TSK-LUM-103-3",
    orderId: "ORD-LUM-103",
    studioId: "lumina-studios",
    title: "Mini-Coffee Table Album Layout",
    serviceCategory: "ALBUM",
    assignedMemberId: "demo-user-deepak",
    assignedMemberName: "Deepak Verma",
    status: "IN_PROGRESS",
    sequenceOrder: 3,
    createdAt: "2026-08-20T11:00:00.000Z",
    updatedAt: "2026-09-08T09:30:00.000Z",
  },

  // ORD-LUM-104 (Completed)
  {
    id: "TSK-LUM-104-1",
    orderId: "ORD-LUM-104",
    studioId: "lumina-studios",
    title: "RAW Photos Review & Selection",
    serviceCategory: "PHOTOGRAPHY",
    assignedMemberId: "demo-user-priya",
    assignedMemberName: "Priya Nair",
    status: "COMPLETED",
    sequenceOrder: 1,
    createdAt: "2026-07-28T09:00:00.000Z",
    updatedAt: "2026-08-20T10:00:00.000Z",
  },
  {
    id: "TSK-LUM-104-2",
    orderId: "ORD-LUM-104",
    studioId: "lumina-studios",
    title: "Fine Art Portrait Retouching",
    serviceCategory: "PHOTOGRAPHY",
    assignedMemberId: "demo-user-rohan",
    assignedMemberName: "Rohan Mehta",
    status: "COMPLETED",
    sequenceOrder: 2,
    createdAt: "2026-07-28T09:00:00.000Z",
    updatedAt: "2026-08-23T16:00:00.000Z",
  },
  {
    id: "TSK-LUM-104-3",
    orderId: "ORD-LUM-104",
    studioId: "lumina-studios",
    title: "Keepsake Hardcover Album Print & Dispatch",
    serviceCategory: "ALBUM",
    assignedMemberId: "demo-user-deepak",
    assignedMemberName: "Deepak Verma",
    status: "COMPLETED",
    sequenceOrder: 3,
    createdAt: "2026-07-28T09:00:00.000Z",
    updatedAt: "2026-08-28T14:00:00.000Z",
  },

  // ORD-LUM-105 (Awaiting Event)
  {
    id: "TSK-LUM-105-1",
    orderId: "ORD-LUM-105",
    studioId: "lumina-studios",
    title: "Lookbook RAW Culling & Selection",
    serviceCategory: "PHOTOGRAPHY",
    assignedMemberId: "demo-user-arjun",
    assignedMemberName: "Arjun Sharma",
    status: "ASSIGNED",
    sequenceOrder: 1,
    createdAt: "2026-08-25T13:00:00.000Z",
    updatedAt: "2026-08-25T13:00:00.000Z",
  },
  {
    id: "TSK-LUM-105-2",
    orderId: "ORD-LUM-105",
    studioId: "lumina-studios",
    title: "Editorial Skin Retouching & Color Match",
    serviceCategory: "PHOTOGRAPHY",
    assignedMemberId: "demo-user-rohan",
    assignedMemberName: "Rohan Mehta",
    status: "ASSIGNED",
    sequenceOrder: 2,
    createdAt: "2026-08-25T13:00:00.000Z",
    updatedAt: "2026-08-25T13:00:00.000Z",
  },

  // ORD-LUM-106 (Completed)
  {
    id: "TSK-LUM-106-1",
    orderId: "ORD-LUM-106",
    studioId: "lumina-studios",
    title: "RAW Photos Review & Selection",
    serviceCategory: "PHOTOGRAPHY",
    assignedMemberId: "demo-user-arjun",
    assignedMemberName: "Arjun Sharma",
    status: "COMPLETED",
    sequenceOrder: 1,
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-08-10T11:00:00.000Z",
  },
  {
    id: "TSK-LUM-106-2",
    orderId: "ORD-LUM-106",
    studioId: "lumina-studios",
    title: "Gala Banquet Retouching & Highlights",
    serviceCategory: "PHOTOGRAPHY",
    assignedMemberId: "demo-user-priya",
    assignedMemberName: "Priya Nair",
    status: "COMPLETED",
    sequenceOrder: 2,
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-08-14T17:00:00.000Z",
  },
  {
    id: "TSK-LUM-106-3",
    orderId: "ORD-LUM-106",
    studioId: "lumina-studios",
    title: "Commemorative Jubilee Album Bound Print",
    serviceCategory: "ALBUM",
    assignedMemberId: "demo-user-deepak",
    assignedMemberName: "Deepak Verma",
    status: "COMPLETED",
    sequenceOrder: 3,
    createdAt: "2026-07-10T10:00:00.000Z",
    updatedAt: "2026-08-18T16:30:00.000Z",
  },
];
